Bootstrap:docker
From:nfcore/base:latest

%labels
	MAINTAINER Lauri Mesilaakso <lauri.mesilaakso@regionostergotland.se>
	DESCRIPTION Singularity container for JASEN microbiology WGS pipeline (except building final HTML report)
	VERSION 0.3.0

%environment
        export PATH="/opt/conda/envs/jasen/bin:$PATH"
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

%files
        env.yml /environment.yml

%post
        apt update && apt -y upgrade
        apt install --no-install-recommends -y build-essential make curl unzip locales
        #apt install -y build-essential make curl unzip locales

        /opt/conda/bin/conda update -n base -c defaults conda
        #/opt/conda/bin/conda install mamba -n base -c conda-forge
        /opt/conda/bin/conda env create -f /environment.yml
        
        conda clean -a
        apt-get clean
        rm -rf /var/lib/apt/lists/\* /tmp/\* /var/tmp/*

%runscript
        . /opt/conda/bin/activate jasen
	exec "$@"
